### PR TITLE
Removes Zend_Service_Technorati - Fixes #552

### LINKED ISSUE #552: Technorati API is probably no longer available
- Listed as "Deprecated" on http://www.programmableweb.com/api/technorati
- Dissapeared http://www.programmableweb.com/news/technorati-api-disappears-no-longer-representing-technorati/2010/03/04
- API base URL cannot be reached - http://api.technorati.com

cc @froschdesign @akrabat @weierophinney

### PR DESCRIPTION
**Pull request by froschdesign**

### CODE REVIEW

**Comment by froschdesign** [comment]
Related to #552

**Comment by froschdesign** [comment]
ping @akrabat

**Comment by froschdesign** [comment]
ping @akrabat

**Comment by akrabat** [comment]
I have no idea how I missed the first ping!

**Comment by froschdesign** [comment]
> I have no idea how I missed the first ping!

No problem!

**Pull request merged**
