### PR TITLE
Allow overriding cache id and tag validation in Zend_Cache

### PR DESCRIPTION
**Pull request by froschdesign**
Closes #317

### CODE REVIEW

**Comment by mhujer** [comment]
The inheritance may be a way of extending, therefore the `protected` stuff should be considered as a part of the API (in general). But those changes look fine to me.

**Comment by froschdesign** [comment]
> therefore the `protected` stuff should be considered as a part of the API (in general)

`protected` is not a part of the public API.

**Comment by akrabat** [comment]
Agreed. Our policy has always been that we don't keep BC for `protected`.

**Comment by froschdesign** [comment]
No problems on Travis: https://travis-ci.org/froschdesign/zf1/builds/46177629

**Comment by froschdesign** [comment]
ping @akrabat

**Pull request merged**
