### PR TITLE
#744 Zend_Locale_Math fix round numbers to float with put correct dec…

### PR DESCRIPTION
**Pull request by kilatib**
Fix Issue: 744

### CODE REVIEW

**Comment by froschdesign** [comment]
We are sorry, but [ZF1 reaches its End of Life (EOL)](https://framework.zend.com/blog/2016-06-28-zf1-eol.html).

**Comment by froschdesign** [comment]
We do not accept PR's anymore.

**Comment by Pooky** [comment]
@froschdesign When ZF1 reaches its End of Life (EOL), is there posibility to continue under another name ("fork" it for example as OpenZF1) and continue with atleast some bug fixing and security changes in ZF1? 

I'm asking due to some license issues and brand owner ship. Also, ZF1 is great piece of work, with great documentation and it would be pitty, just to let him die. I think many of developers still use it and they would benefit from that.

**Comment by froschdesign** [comment]
@Pooky 
> is there posibility to continue under another name ("fork" it for example as OpenZF1) and continue with atleast some bug fixing and security changes in ZF1?

The Zend Framework _is_ and _was_ an **open source**  project: https://github.com/zendframework/zf1/blob/master/LICENSE.txt
Or see in every project file. (e.g. [Layout.php](https://github.com/zendframework/zf1/blob/master/library/Zend/Layout.php#L5))

You can fork the project every time as long as you honour the current license terms!

> "fork" it for example as OpenZF1

In my opinion "OpenZF1" is a wrong name, because the Zend Framework is already open!

> Also, ZF1 is great piece of work…

I see some problems:

* The official support for ZF1 was PHP 5.6; no PHP7! PHP 5.6 has no active support since 8 months. Active support for PHP 7.0 ends in 1 month. The current version is 7.1 and 7.2 is around the corner.
* The MVC part of ZF1 is unflexibel and many components are obsolete or outdated.
* And the main reason: ZF1 is no longer supported!

Btw. with zend-expressive you have a powerful option to migrate your ZF1 application.

**Comment by Pooky** [comment]
@froschdesign Thanks for answer!

Your are right, I read the license file and there is not restriction from Zend side. By "fork" I mean create copy of current state and continue to accept patches, when someone find bug or update current feature. 
For example, I would be interested to see, if ZF1 will run on PHP 7.1 with small changes or updates. 

To the problems, you are of course also right, ZF1 was created long time ago and miss some curent features, which are so much trendy, but it's incredibly stable, easy to extend and well-documented. I went throught the new verison ZF2, ZF3 and they are really nice but meaby to much overkill, for simple applications.  To me it seems that they try too hard to copy Java ecosystem. Composer, modules, dependency injection, middleware and so on. I understand that there is place for this things but for my and other's it's just overcomplexity, which will be seldom used. In my point of view, framework should help you to make Models, Views, Controllers, it should help you to handle forms, validation, translation and other things easy, without much of configuration (something like Spring-Boot but PHP way), ZF1 used to do this really nicely, it's easy to register plugin, to add new helper, to make new form, it came with standartized elements and many other features well documented. For me it's too much benefit, to switch from it just for the speed improvement in PHP7 or some features "which-will-meaby-usefull-in-future". I like when things are well done and documented.

**Comment by froschdesign** [comment]
@Pooky 
> Your are right, I read the license file and there is not restriction from Zend side. By "fork" I mean create copy of current state and continue to accept patches, when someone find bug or update current feature.
For example, I would be interested to see, if ZF1 will run on PHP 7.1 with small changes or updates.

It's open: you can do all these things and create a community around your fork. No problem, the license allows it. 

> miss some curent features, which are so much trendy, but it's incredibly stable

Oh no, trendy or new shiny features are not a goal. But many components of ZF1 are obsolete or outdated, like `Zend_Date`, `Zend_Locale`, `Zend_Form`, `Zend_Validate`, `Zend_Captcha`, `Zend_Crypt`, `Zend_Service`, `Zend_View`, `Zend_Rest` etc.

> they are really nice but meaby to much overkill, for simple applications.

Sorry, but this is wrong. ZF1 is overkill for simple application! Create an application with zend-expressive, Slim or others of the same type and you know what I mean.

> Composer, modules, dependency injection, middleware and so on. I understand that there is place for this things but for my and other's it's just overcomplexity…

And the same here: exactly the opposite is the case! Compare a ZF1 controller and a Middleware action – don't forgot the (unit) testing. And if you look the MVC pattern then compare a ZF1 and ZF2/3 controller.

> ZF1 used to do this really nicely…

…and too complicated! 😉

**Comment by Pooky** [comment]
@froschdesign Thanks for the information. 

I see your point but I think this is really specific in your field of work or expertise. I would argue that many regular webdeveloper focus less and less on serverside of webapplication and more on the client side. For them is this "shift" to middleware and more robust applications not really benefit.

 I understand the need for some complex (corporate) features like type hint for variables, namespaces, dependency injection, security or rbac control but that's just for some small subset of developers which adopt PHP afterwards. In the past, the PHP and ZF1 was popular because it was easy to use and you can do almost anything without any restriction. I would compare it to Javascript. Javascript was also sucessfull in the past, yet everyone complained that it's terrible so there come ECMAScript 2016, Node.js, NPM and so on, basicly the corporate adopt the language and add some their features, which makes it again the language which is not easy to use. Today ECMAScript 2016 will never be so much spread and used as pure javascript, it's differend language which is compatible to javascript. 

Back to the point, for me personaly it's worth to continue with ZF1 and try to adapt it for PHP7, HTML5 tags in form elements and also try to more integrate it with javascript. There is also great feature of context switching, which makes increadibly easy to use Ajax and fetch data from server. I don't know if this features are also in ZF2/3 but I coudn't find them in documentation or some other resource, even if I tried.

**Comment by froschdesign** [comment]
@Pooky  
I think you misunderstood me. I never said you must or should shift to the middleware solution. You should look at it and try it out. Nothing more!

> I think this is really specific in your field of work or expertise.

That's only your feeling, but not true!

> …more robust applications not really benefit.

My free time is worth something to me. I prefer robust applications and thus less bug fixing. I'm too lazy for unstable or buggy applications. 😄  

> I would argue that many regular webdeveloper focus less and less on serverside of webapplication and more on the client side.

I know what you mean, but no.
In your case – more "client side" and less "server side" –  I have another suggestion for your: [Apigility](https://apigility.org/) - all freedom on client side and server side with backend.

> but I coudn't find them in documentation or some other resource, even if I tried.

Do you mean something like that: "[Controller Plugins - AcceptableViewModelSelector Plugin](https://docs.zendframework.com/zend-mvc/plugins/#acceptableviewmodelselector-plugin)"

---

Another import point I have not yet mentioned: ZF1 is a "dead horse". I say this reluctantly, but it corresponds to reality.
Last bugfix release was on 13.04.2016. No feature release since years!

**Comment by Pooky** [comment]
@froschdesign Well, then we should buy a stronger whip, change wheel and reclassifying the horse as old and stable.

I know Apigility, I  use ZF1 since 2008 (or 2009) so I also follow development and new projects from Zend. Anyway, the expression 
> more "client side" and less "server side" 
doesn't mean to use only client side, like Angular or React, which would be possible with Apigility. This one-page apps written only JS has some real downsides and I was witness how after boom of Angular in 2013 companies returning back to old good server side rendering with included javascript. What I really ment with this statement was that developers (or atleast I) want to focus more on integration and overall expireince for user than on serverside framework. Basicly, I want something like Bootstrap but for PHP on Serverside, I want to have basic skeleton which works, all possible things which I can use right away (file upload, forms, css, viewhelpers etc. ) prepared and ready to use and I want compatibility. I don't want to dig what happend in new version, I don't really need new version and just need to accomplish the task with what is in hand. If new version will use some incredibly usefull feature all right, but don't made it mandatory or default. 

I looked on ZF3 "Controller Plugins - AcceptableViewModelSelector Plugin", it's probably the context switching from ZF1. I went throught other resources and the tutorial and I can't help it, but the documentation is terrible, there is this lending page with all cool modules which everyone exactly need right away - https://docs.zendframework.com/, so you wan't to now how use Forms in new zend, you click and it you are here :https://docs.zendframework.com/zend-form/ there is nothing. Also whole ZF2/ZF3 documentation has terrible font and formating (one example: https://docs.zendframework.com/zend-mvc/services/).

One thing which was reason why I choose to use Zend instead of other's was the perfect documentation. And it still is, here on GitHub https://github.com/zendframework/zf1/wiki or on official page: https://framework.zend.com/manual/1.12/en/manual.html you can find everything easily and really fast.

**Comment by froschdesign** [comment]
> you click on link and you are here: https://docs.zendframework.com/zend-form/ there is nothing.

Oh, no. Please look at the navigation top bar:

form

* Intro
* Quick start
* Reference
  * Elements
     * …
  * Collections
  * File Uploads
  * View Helpers
     * …
  * Advanced

**Comment by tavy315** [comment]
@Pooky, I'm using ZF1 in production with PHP 7.0 and had no problems with it so far. Btw, forked the main project a long time ago: https://packagist.org/packages/tavy315/zendframework1

**Comment by holtkamp** [comment]
> I'm using ZF1 in production with PHP 7.0 and had no problems with it so far.

Same here, running it without any in problems on PHP 7.1. Currently in the process of gradually phasing out ZF1 components. You can use https://github.com/zf1 to only use specific parts, documentation at https://github.com/zf1/zend-application

**Comment by Pooky** [comment]
That`s great news. I will give it shot, I really like the features and performance of PHP 7 and it would be pitty not to try that.

**Pull request closed without merging**
