### PR TITLE
$this can not be unset

### PR DESCRIPTION
**Pull request by glensc**
Fatal error: Cannot unset $this in library/Zend/Service/WindowsAzure/Storage/Batch.php on line 108

### CODE REVIEW

**Comment by froschdesign** [comment]
We are sorry, but [ZF1 reaches its End of Life (EOL)](https://framework.zend.com/blog/2016-06-28-zf1-eol.html).

**Comment by glensc** [comment]
perhaps turn the project into community project instead of killing MR's. i'm sure there are volunteers

**Comment by froschdesign** [comment]
Zend Framework is a community project. I am also part of the community and not a "Zend employee", but that does not matter! **ZF1 is no longer supported** ([except for Enterprise users of Zend Server](http://www.zend.com/en/support-center/support/production-sla)).

Use your own fork and all is fine.

**Comment by glensc** [comment]
by "community effort" i mean, it gets moved out of zend "official" repositories (perhaps new github organization `zf1`?), so Zend Enterprise is no longer linked-to/blamed-for the product, and interested parties could continue maintaining it. not each one having their own fork.

and statement `zf1 is no longer supported`, means zend does not support it.

**Comment by akrabat** [comment]
@glensc You are free to fork the project as long as you honour the current license terms for all existing code. You can then create a community around your fork.

**Pull request closed without merging**
