### PR TITLE
Save time and space when cloning PHPUnit

### PR DESCRIPTION
**Pull request by PowerKiKi**
On my particular set up it is twice faster and more than 4 times smaller to do it that way

### CODE REVIEW

**Comment by PowerKiKi** [comment]
Just sent my CLA. Also failing tests are not related to this patch. My patch target specifically PHP 5.2 but the failures are only with PHP 5.4

**Comment by froschdesign** [comment]
@akrabat 
CLA is present.

**Comment by froschdesign** [comment]
@akrabat 
Can you look at this?

**Comment by akrabat** [comment]
I can indeed. Thanks @PowerKiKi !

**Comment by froschdesign** [comment]
@akrabat 
Thanks! :+1:

**Pull request merged**
