### PR TITLE
Fix ZF-7570: forceIndex, useIndex, ignoreIndex methods on db select and join. 

### PR DESCRIPTION
**Pull request by ezequielp**
This PR is a replacement for #509.

### CODE REVIEW

**Comment by mhujer** [comment]
@ezequielp The tests are failing on travis

**Comment by ezequielp** [comment]
Trying again. I made a mistake on the tests.

**Comment by Alez** [comment]
Any updates on that?

**Comment by ezequielp** [comment]
This is fixed but never got pushed

**Comment by ezimuel** [comment]
@ezequielp I don't agree to put specific vendor SQL syntax in Zend_Db_Select. The actual design of Zend_Db doesn't allow to have specific SQL dialect. As you also commented [here](https://github.com/ezequielp/zf1/blob/master/library/Zend/Db/Select.php#L1406) this will work only for MySQL. 

A better architecture design should have a subclass of Zend_Db_Select in each Adapter with specific SQL syntax, but this would require an heavy refactor of the actual implementation and unfortunately this is not possible at the actual stage of ZF1.

A workaround to use [Hint](https://en.wikipedia.org/wiki/Hint_(SQL)) SQL features is to use an explicit syntax with [Zend_Db_Statement](http://framework.zend.com/manual/1.12/en/zend.db.statement.html), for instance:
```php
$stmt = $db->query('SELECT `p`.* FROM `product` AS `p` FORCE INDEX(?)');
$stmt->execute(array('IX_this_index_does_not_exist'));
```

I'm very sorry but I cannot merge this MySQL feature in Zend_Db :(
/cc @froschdesign, @mhujer, @Alez, @dbaltas, @weierophinney

**Comment by froschdesign** [comment]
I close this pull request, because:

> …this would require an heavy refactor of the actual implementation and unfortunately this is not possible at the actual stage of ZF1.

**Comment by dbaltas** [comment]
ok, makes sense

**Comment by tasmaniski** [comment]
Actually, you can set this option. 
So, if you still want to use Zend Db/TDG 

```
$select = new Select;    // instance of \Zend\Db\Sql\Select
$select->.... 
$select->setSpecification(Select::SELECT, [
            'SELECT %1$s FROM %2$s USE INDEX (yor_index_name)' => [
                [1 => '%1$s', 2 => '%1$s AS %2$s', 'combinedby' => ', '],
                null
            ],
            'SELECT %1$s %2$s FROM %3$s'                        => [
                null,
                [1 => '%1$s', 2 => '%1$s AS %2$s', 'combinedby' => ', '],
                null
            ],
            'SELECT %1$s'                                       => [
                [1 => '%1$s', 2 => '%1$s AS %2$s', 'combinedby' => ', '],
            ],
]);
```


Basically you need to override default specification for queries you want 
https://github.com/zendframework/zend-db/blob/master/src/Sql/Select.php#L68

work like a charm :)

**Comment by froschdesign** [comment]
@tasmaniski 
`Zend\Db\Sql\Select` is a part of ZF2/3. Not ZF1!

**Pull request closed without merging**
