### PR TITLE
Solve problem with subqueries in SELECT block

### PR DESCRIPTION
**Pull request by erdraug**
> Next try https://github.com/zendframework/zf1/pull/627

It solves executing queries with subqueries in SELECT block.
"New line" char (which is added in _renderFrom function while imploding joins) causes problem in regexp for "AS" case detection.
Now I've change not the cause but the result of the problem. In this way the problem is solved without global code changes.

### CODE REVIEW

**Comment by froschdesign** [comment]
ping @ezimuel

**Comment by erdraug** [comment]
Hello, @froschdesign
Do you have any prognosis when this request can be resolved?

**Comment by ezimuel** [comment]
@erdraug very nice solution, thanks! /cc @froschdesign

**Comment by froschdesign** [comment]
@erdraug and @ezimuel
Thanks! :+1:

**Comment by erdraug** [comment]
Hello, @froschdesign could you predict a release date of ZF 1.12.18?

**Comment by froschdesign** [comment]
@erdraug 
Next Tuesday (12 Apr).

**Comment by erdraug** [comment]
@froschdesign Hurrah! Thanks :+1:

**Pull request merged**
