### PR TITLE
Fix regexp to detect functions in column definition

### PR DESCRIPTION
**Pull request by foxel**
Fixed for unbalanced parentheses and deeply nested functions

### CODE REVIEW

**Comment by foxel** [comment]
Related to #441

**Comment by foxel** [comment]
BTW. CLA signed

**Comment by froschdesign** [comment]
ping @ezimuel

**Comment by akrabat** [comment]
Do we need this for 1.12.12 ?

**Comment by froschdesign** [comment]
The unit tests looks good to me.

**Comment by foxel** [comment]
Updated to include more tests

**Comment by foxel** [comment]
Hi!
What response is awaited from me?
Travis failed on pecl and CLA is signed (Matthew Weier O'Phinney: There's a problem with the tool that integrates with github; the api it checks against is, however, correctly showing your cla status.)

**Comment by froschdesign** [comment]
@foxel 
> What response is awaited from me? 

None! (A review is needed. Thanks for the hint.)

**Comment by froschdesign** [comment]
Thanks to @foxel and @ezimuel!

**Pull request merged**
