### PR TITLE
Automatically pass an x-request-id header in HTTP requests if UNIQUE_ID value is set

### PR DESCRIPTION
**Pull request by blockjon**
I have found this to be useful in order to help trace how requests are sent to various internal microservices within our system. I'd like to see this, or something like, it make it into the framework.

### CODE REVIEW

**Comment by froschdesign** [comment]
Sorry, but I can not find a signed [CLA](https://github.com/zendframework/zf1/wiki/Contributor-License-Agreement-%28CLA%29).

**Comment by blockjon** [comment]
The last time I tried it i got:
```
Delivery to the following recipient failed permanently:

     cla@zend.com:

Technical details of permanent failure:
Internal parse error: Illegal envelope To: address (invalid domain name): cla@zend.com:
```

**Comment by froschdesign** [comment]
Some more informations to `UNIQUE_ID`: http://httpd.apache.org/docs/2.2/mod/mod_unique_id.html

**Comment by froschdesign** [comment]
@blockjon 
Please contact @weierophinney. Thanks!

**Comment by blockjon** [comment]
@weierophinney sorry to call out to you on a random ticket - I swear I had send in my cla last year after it had bounced. What's the best email for me to forward my signed cla to at this point? I still have the bounced copy from last year when I tried it in my inbox.

**Comment by blockjon** [comment]
@froschdesign Pretty sure that's already the origin of our web request ID's are.. however, when we debug our systems in production, it is *extremely* useful for the ID generated by the front end to pass through to the micro services that we call to via HTTP requests. It is for this reason that having the unique id automatically pass through somehow would be highly desired. Even without my cla, maybe you have some alternate idea that can be used to achieve this?

**Comment by froschdesign** [comment]
@blockjon 
Look at the Github page of @weierophinney there you can find an email address.

**Comment by froschdesign** [comment]
@blockjon 
> …it is extremely useful for the ID generated by the front end to pass through to the micro services that we call to via HTTP requests.

That's not the question. We need a use case *and* unit tests!

And please remember:
> For ZF1, we are accepting bug fixes to existing components.

http://framework.zend.com/participate/contributor-guide-v1

**Comment by froschdesign** [comment]
Closed, because:

- no unit test was provided
- it's a feature request

**Pull request closed without merging**
