### PR TITLE
Fix for #511 - Add PATCH to the list of allowed methods in Zend_Controller_Request_HttpTestCase

### PR DESCRIPTION
**Pull request by elightbo**
Adds patch to the list of valid method types array.

### CODE REVIEW

**Comment by akrabat** [comment]
@elightbo Have you signed the CLA?

**Comment by elightbo** [comment]
@akrabat I haven't yet, but will on Monday when I have access to a printer.

**Comment by elightbo** [comment]
@akrabat I signed the CLA, and @weierophinney just processed it. Thanks :)

**Comment by froschdesign** [comment]
@akrabat 
CLA is present.

**Comment by froschdesign** [comment]
@elightbo 
Please add an unit test for all methods. Thanks!

**Comment by elightbo** [comment]
Just curious why your'e not needing unit tests anymore. Thanks!

**Comment by froschdesign** [comment]
@elightbo 
See dea39d4770083314124107e4266c2f13b417222d

**Comment by elightbo** [comment]
@froschdesign Got it. I promise my next contributions will be unit tested. Thank you :)

**Pull request merged**
