### PR TITLE
Run travis build also on PHP 7 builds

### PR DESCRIPTION
**Pull request by mhujer**
See https://github.com/travis-ci/travis-ci/issues/2480#issuecomment-75988205

### CODE REVIEW

**Comment by mhujer** [comment]
@froschdesign wanted to wait for the build to see if it does not fail much :-)

**Comment by froschdesign** [comment]
@mhujer 
There is no build: https://travis-ci.org/zendframework/zf1/builds

**Comment by mhujer** [comment]
Yeah, it looks like it is not being build... strange

**Comment by mhujer** [comment]
http://www.traviscistatus.com/incidents/bc3jgcrjs7gt

**Comment by froschdesign** [comment]
@mhujer 
See 9b0223a34e216b269bdd53916cc82405aecaad56

**Comment by mhujer** [comment]
:+1: 

It looks like that there are almost no failures (except for the missing memcache(d) extension)

**Comment by akrabat** [comment]
Yeah. Good news, so far :)

**Pull request merged**
