### PR TITLE
Allow checkbox elements with custom index

### PR DESCRIPTION
**Pull request by mansurs**
Allow checkbox elements with custom index

### CODE REVIEW

**Comment by mansurs** [comment]
CLA should be signed now.

**Comment by froschdesign** [comment]
@mansurs 
Please add also an unit test to illustrate the problem.

**Comment by mansurs** [comment]
It seems that the problem is fixed. We are coming from 1.11.3 version and we had a problem with. Sorry to bother. I will close the PR

**Comment by froschdesign** [comment]
> Sorry to bother.

No problem. Thanks for the feedback.

**Pull request closed without merging**
