### PR TITLE
Added more specific return documentation for Zend_Navigation Pages

### PR DESCRIPTION
**Pull request by holtkamp**
To improved code-completion in IDEs like PHPStorm

### CODE REVIEW

**Comment by froschdesign** [comment]
Is this data type supported by phpDocumentor?

**Comment by Ocramius** [comment]
@froschdesign it's used across a lot of OSS projects, as far as I know. Not sure if PHPDocumentor supports it, but it's _REALLY_ useful.

**Comment by froschdesign** [comment]
> but it's REALLY useful.

I know, I use this already.

**Comment by holtkamp** [comment]
additionally, if adopted, it also prevents the need of documentation like "array containing only Zend_Navigation_Page instances"

**Comment by froschdesign** [comment]
@holtkamp 
Go!

**Pull request merged**
