### PR TITLE
doc fix Zend_Dojo_View_Helper_CheckBox->checkBox

### PR DESCRIPTION
**Pull request by thoys**

### CODE REVIEW

**Comment by froschdesign** [comment]
We are sorry, but ZF1 reaches its End of Life (EOL).

**Comment by thoys** [comment]
Still one month and 10 days.. It is just a small doc fix nothing big...

**Comment by froschdesign** [comment]
@thoys 

> …we will only be accepting security patches…

https://github.com/zendframework/zf1#readme

**Comment by thoys** [comment]
I'll just keep a private fork to keep my fixes. Sorry for bothering.

**Comment by froschdesign** [comment]
No problem!

**Pull request closed without merging**
