### PR TITLE
Added @method PHPDocumentation for ViewHelpers

### PR DESCRIPTION
**Pull request by holtkamp**
Not yet complete, but these are used most often

### CODE REVIEW

**Comment by froschdesign** [comment]
> Not yet complete

Please add all (standard) helpers.

**Comment by froschdesign** [comment]
ping @holtkamp

**Comment by holtkamp** [comment]
ping @froschdesign, I completed the list, but the function parameters are still a to-do which are (too) time consuming for me right now... Hope this PR can be merged so we can go one step at a time..

**Comment by froschdesign** [comment]
@holtkamp 
The syntax is wrong. Please compare with: http://www.phpdoc.org/docs/latest/references/phpdoc/tags/method.html

```php
class Parent
 {
     public function __call()
     {
         <...>
     }
 }

 /**
  * @method string getString()
  * @method void setInteger(integer $integer)
  * @method setString(integer $integer)
  */
 class Child extends Parent
 {
     <...>
 }
```

**Comment by froschdesign** [comment]
@holtkamp 
See also: https://github.com/froschdesign/zf1/commit/b9af1d7465e05c0b5c9ff499db4fede7a3448bf2

**Comment by holtkamp** [comment]
Aah, you are right. On our projects we tend to return the Helper object and use a ```render()``` method to acquire the result. Sorry about that, was in a hurry, not the right way ;)

**Comment by froschdesign** [comment]
No problem, because the basic idea is good!

**Pull request closed without merging**
