### PR TITLE
Installs PHPUnit via apt-get instead of via PEAR.

### LINKED ISSUE #493: PHPUnit not being installed
After run step 6 of DEVELOPMENT_README.md the following message is shown:

    ...
    Installing PHPUnit
    Updating channel "doc.php.net"
    Update of Channel "doc.php.net" succeeded
    Updating channel "pear.php.net"
    Channel "pear.php.net" is up to date
    Updating channel "pecl.php.net"
    Channel "pecl.php.net" is not responding over http://, failed with message: File http://pecl.php.net:80/channel.xml not valid (redirected but no location)
    Trying channel "pecl.php.net" over https:// instead
    Channel "pecl.php.net" is up to date
    Will upgrade channel://pear.php.net/archive_tar
    downloading Archive_Tar-1.3.13.tgz ...
    Starting to download Archive_Tar-1.3.13.tgz (19,891 bytes)
    .......done: 19,891 bytes
    upgrade-all ok: channel://pear.php.net/Archive_Tar-1.3.13
    config-set succeeded
    Attempting to discover channel "pear.phpunit.de"...
    downloading End-of-Life-for-PEAR-Installation-Method ...
    Starting to download End-of-Life-for-PEAR-Installation-Method (Unknown size)
    ......done: 28,088 bytes
    unknown channel "pear.phpunit.de" in "pear.phpunit.de/PHPUnit-3.4.15"
    invalid package name/package file "pear.phpunit.de/PHPUnit-3.4.15"
    install failed

    PHP version 5.5.20 is now installed. Type: pe 5.5.20

Running example lines of step 7 the following error can be viewed:

    The program 'phpunit' is currently not installed.  You can install it by typing:
    sudo apt-get install phpunit

### PR DESCRIPTION
**Pull request by pkelbert**
Fixes #493

### CODE REVIEW

**Comment by pkelbert** [comment]
Build failures are not due to branche's content. According to lines 565-625 of Travis job -- https://travis-ci.org/zendframework/zf1/jobs/47563619 -- Zend/Feed has issues.

**Comment by froschdesign** [comment]
@pkelbert 
This is a temporarily error.

**Comment by froschdesign** [comment]
ping @mhujer

**Comment by mhujer** [comment]
@pkelbert I have no idea which PHPUnit version is gonna be installed through the apt-get. But the last PHPUnit version which supports PHP 5.2 is 3.6, so maybe the similar way which is used for travis can be used here. See https://github.com/zendframework/zf1/pull/482

**Comment by pkelbert** [comment]
@mhujer The version being installed via apt-get is 3.4.5 but in fact it would be better to have control over which version is installed and your solution seems to be way better. I'm going to checkout how to use the solution adopted on #482 on Vagrant provisioning.

**Comment by thetreewithin** [comment]
it might be better @pkelbert because it's not a good idea to have binary paths hardcode, neither use sudo on a shell script

**Comment by froschdesign** [comment]
@akrabat 
Can you look at this?

**Comment by akrabat** [comment]
I can do.
@pkelbert Did you get anywhere with looking at the #482 solution?

**Comment by akrabat** [comment]
Thanks!

**Comment by pkelbert** [comment]
Sorry for the late answer @akrabat 
I did some work on trying same approach as #482 but didn't go much far.

**Pull request merged**
