### PR TITLE
Implode join without "new line" char.

### PR DESCRIPTION
**Pull request by erdraug**
It solves problem with subqueries with joins in SELECT block

### CODE REVIEW

**Comment by froschdesign** [comment]
@erdraug 
Sorry, but I can not find a signed [CLA](https://github.com/zendframework/zf1/wiki/Contributor-License-Agreement-%28CLA%29).

**Comment by froschdesign** [comment]
@erdraug 
Please check Travis:

> Zend_Db_Select_MysqliTest::testAssembleQueryWithSubqueryInSelectBlock
Assembling query with subquery with join failed

https://travis-ci.org/zendframework/zf1/jobs/84881973#L678

**Comment by erdraug** [comment]
I've fixed my test and sent CLA via email (alexskomarov@gmail.com).

**Comment by erdraug** [comment]
Hello, @froschdesign 
I've fixed fail of my test and sent a CLA. It's already received.
Can you merge it now?

**Comment by froschdesign** [comment]
@erdraug 
I can still see problems:

1. You changed existing unit tests.
2. Your changes produce different results / different SQL queries.

We need a fix without these problems / changes.

**Comment by erdraug** [comment]
Next try https://github.com/zendframework/zf1/pull/628

**Pull request closed without merging**
