### PR TITLE
Fixes #436 - CLDR v26 released

### LINKED ISSUE #436: CLDR v26 released
A new CLDR version has been released.

http://cldr.unicode.org/index/downloads/cldr-26

### PR DESCRIPTION
**Pull request by froschdesign**

### CODE REVIEW

**Comment by akrabat** [comment]
Any updates on this one, @froschdesign?

**Comment by froschdesign** [comment]
@akrabat 
There are many strange changes. For example:
```
1) Zend_DateTest::test_ToString
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-01.01.1970 05:00:00
+01. Jän. 1970 05:00:00
```
I will look for a solution.

**Comment by akrabat** [comment]
I think we should release 1.12.10 soon-ish. Do you want to get this one into it?

**Comment by froschdesign** [comment]
@akrabat 
There are too many problems with the whole implementation of `Zend_Date`.

For example:
If the date time format includes the german word "um", then the extraction of the date parts breaks.

```xml
<dateTimeFormatLength type="full">
    <dateTimeFormat>
        <pattern>{1} 'um' {0}</pattern>
    </dateTimeFormat>
</dateTimeFormatLength>
```
https://github.com/froschdesign/zf1/blob/hotfix/436/library/Zend/Locale/Data/de.xml#L1428

```php
$min = iconv_strpos($format, 'm');
```
https://github.com/froschdesign/zf1/blob/hotfix/436/library/Zend/Locale/Format.php#L831

:-1:

**Comment by froschdesign** [comment]
I think, the `Zend_Date` component is deprecated, error-prone and to fat.

**Pull request closed without merging**
